version: "3.9"

services:
  postgres:
    image: postgres:16.4
    container_name: taskmaster_server_db
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskmaster_db
    command: postgres -c log_statement=all

#  liquibase:
#    image: liquibase/liquibase
#    container_name: liquibase
#    depends_on:
#      - postgres
#    environment:
#      LIQUIBASE_SEARCH_PATH: ./changelog/db/changelog
#    volumes:
#      - ./src/main/resources:/liquibase/changelog
#    command:
#      [ "/liquibase/liquibase",
#        "--changeLogFile=db.changelog-master.yaml",
#        "--url=jdbc:postgresql://transfer_db:5432/transfer_service_db",
#        "--username=postgres",
#        "--password=postgres",
#        "update" ]