version: "3.9"

networks:
  taskmasterserver-network:
    driver: bridge

services:
  taskmasterserver:
    image: taskmasterserver:slim
    networks:
      - taskmasterserver-network
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://taskmaster_server_db:5432/taskmaster_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      CHANGELOG: classpath:/db/changelog/db.changelog-master.yaml

  postgres:
    image: postgres:16.4
    networks:
      - taskmasterserver-network
    container_name: taskmaster_server_db
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskmaster_db
    command: postgres -c log_statement=all

#  liquibase:
#    image: liquibase/liquibase
#    networks:
#      - taskmasterserver-network
#    container_name: liquibase
#    depends_on:
#      - postgres
#    environment:
#      LIQUIBASE_SEARCH_PATH: ./changelog/db/changelog
#    volumes:
#      - ./src/main/resources:/liquibase/changelog
#    command:
#      [ "/liquibase/liquibase",
#        "--changeLogFile=db.changelog-master.yaml",
#        "--url=jdbc:postgresql://taskmaster_server_db:5432/taskmaster_db",
#        "--username=postgres",
#        "--password=postgres",
#        "update" ]