databaseChangeLog:
  - changeSet:
      id: v1-create-table-application_user
      author: a.cherenkov
      changes:
        - createTable:
            tableName: application_user
            columns:
              - column:
                  name: id
                  type: UUID
                  autoIncrement: false
                  defaultValue: gen_random_uuid()
                  constraints:
                    primaryKey: true
              - column:
                  name: username
                  type: varchar(32)
                  constraints:
                    nullable: false
                    unique: true
              - column:
                  name: email
                  type: varchar(64)
                  constraints:
                    nullable: true
                    unique: true
              - column:
                  name: password
                  type: varchar(64)
                  constraints:
                    nullable: false
              - column:
                  name: created_at
                  type: date
                  constraints:
                    nullable: false
              - column:
                  name: updated_at
                  type: datetime
                  constraints:
                    nullable: false